fix: make setArrivalTime and setBurstTime required properties
this fixes the following compilation error:
"Type error: Cannot invoke an object which is possibly 'undefined'."